# Generated by Django 3.1.12 on 2022-01-18 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreport',
            name='company',
        ),
        migrations.AddField(
            model_name='companyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companyreport', to=settings.AUTH_USER_MODEL),
        ),
    ]
