# Generated by Django 3.1.12 on 2022-01-18 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_auto_20220118_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyreport', to=settings.AUTH_USER_MODEL),
        ),
    ]
