# Generated by Django 3.1.12 on 2022-01-18 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_auto_20220118_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companyreport', to='auth_rest_phone.userprofile'),
            preserve_default=False,
        ),
    ]
