# Generated by Django 3.2.5 on 2022-02-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0004_auto_20220118_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyreport', to=settings.AUTH_USER_MODEL),
        ),
    ]
