# Generated by Django 3.2.9 on 2021-12-04 14:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6)),
                ('father_name', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single')], max_length=7)),
                ('birth_place', models.CharField(max_length=50)),
                ('Place_issuance_identitycard', models.CharField(max_length=50)),
                ('marriage_date', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('identity_serialnumber', models.CharField(max_length=10)),
                ('national_code', models.CharField(max_length=10)),
                ('education', models.CharField(choices=[('bisavad', 'bisavad'), ('ebtedaei', 'ebtedaei'), ('sicl', 'sicl'), ('diplom', 'diplom'), ('kardani', 'kardani'), ('karshenasi', 'karshenasi'), ('karshenasiarshad', 'karshenasiarshad'), ('doctora', 'doctora')], max_length=20)),
                ('job', models.CharField(max_length=50)),
                ('work_address_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('work_address', models.JSONField(blank=True, default=dict, null=True)),
                ('address_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.JSONField(default=dict)),
                ('mobile_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('postalcode', models.CharField(max_length=10)),
                ('insurance_history', models.BooleanField()),
                ('province_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('province_code', models.CharField(blank=True, max_length=5, null=True)),
                ('township_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('township_code', models.CharField(blank=True, max_length=5, null=True)),
                ('part_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('part_code', models.CharField(blank=True, max_length=5, null=True)),
                ('ruraldistrict_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('ruraldistrict_code', models.CharField(blank=True, max_length=5, null=True)),
                ('city_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('city_code', models.CharField(blank=True, max_length=5, null=True)),
                ('village_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.company')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='File_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('shenasnameh', 'shenasnameh'), ('cartmeli', 'cartmeli'), ('image', 'image')], max_length=20)),
                ('files', models.FileField(upload_to='upload/person_files/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='person.person')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ('-created',),
            },
        ),
    ]
