# Generated by Django 3.2.9 on 2021-11-28 09:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('emergency_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('national_code', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=6)),
                ('address_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.JSONField(default=dict)),
                ('files', models.FileField(blank=True, null=True, upload_to='upload/person_files/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.company')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
