# Generated by Django 3.1.12 on 2022-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='identity_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
