# Generated by Django 3.2.9 on 2021-11-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='files',
        ),
        migrations.CreateModel(
            name='File_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('shenasnameh', 'shenasnameh'), ('cartmeli', 'cartmeli'), ('payankhedmat_moafiat', 'payankhedmat_moafiat'), ('image', 'image')], default='shenasnameh', max_length=20)),
                ('files', models.FileField(blank=True, null=True, upload_to='upload/person_files/')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='person.person')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
