# Generated by Django 3.1.12 on 2022-01-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_identity_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identity_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
