# Generated by Django 3.1.12 on 2022-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20220129_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
