# Generated by Django 3.2.9 on 2021-12-01 14:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manager_first_name', models.CharField(max_length=30)),
                ('manager_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('manager_national_code', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('mobile_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('address_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
