# Generated by Django 3.1.12 on 2022-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220118_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager_last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
