# Generated by Django 3.1.12 on 2022-01-31 11:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20220124_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyaddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyaddress_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='company',
            name='homeaddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='homeaddress_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='company',
            name='license_expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(choices=[('MAINSTREET', 'MAINSTREET'), ('AUXILIARYROAD', 'AUXILIARYROAD'), ('DOWNTOWN', 'DOWNTOWN'), ('CITYENTRANCEEXIT', 'CITYENTRANCEEXIT'), ('SUBRUBS', 'SUBRUBS')], max_length=20),
        ),
    ]
