# Generated by Django 3.2.5 on 2022-02-16 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_auto_20220207_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='auth_rest_phone.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
