# Generated by Django 3.2.5 on 2022-02-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
