# Generated by Django 3.2.5 on 2022-02-21 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0011_auto_20220221_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceformupload',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuranceFormUploads_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='insuranceformupload',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceformupload',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceformupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceFormUploads_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
