# Generated by Django 3.1.1 on 2021-09-13 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportation_company', '0004_auto_20210913_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='It will be fill, if you leave it empty. ex: cz6nX', max_length=64, unique=True)),
                ('percentage', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('maximum_value', models.IntegerField(default=0)),
                ('expire_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OccasionalDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percentage', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCodeStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.IntegerField(default=0)),
                ('expire_time', models.IntegerField(default=5)),
                ('is_for_first_order', models.BooleanField(default=False)),
                ('percentage', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('maximum_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=19)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walletss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.CharField(max_length=100, verbose_name='trackingCode')),
                ('bankRefId', models.CharField(blank=True, max_length=100, null=True, verbose_name='bankRefId')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10, verbose_name='status')),
                ('statusNum', models.IntegerField(verbose_name='status number')),
                ('authority', models.CharField(max_length=20, verbose_name='authority')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='user_info.wallets', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='PromotionalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='It will be fill, if you leave it empty. ex: cz6nX', max_length=64, unique=True)),
                ('percentage', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('maximum_value', models.IntegerField(default=0)),
                ('num_of_used', models.IntegerField(default=0, editable=False)),
                ('expire_at', models.DateField()),
                ('disable', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('dr', 'Draft'), ('pa', 'Payed')], default='dr', max_length=4, verbose_name='pay_status')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_from', to='user_info.wallets')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='transportation_company.request')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_to', to='user_info.wallets')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
