# Generated by Django 3.2.5 on 2022-02-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/message_files/')),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('read', 'read'), ('answerd', 'answerd')], max_length=10)),
                ('direction', models.CharField(choices=[('u1tou2', 'u1tou2'), ('u2tou1', 'u2tou1')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.thread'),
        ),
    ]
