# Generated by Django 3.2.5 on 2022-02-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20220214_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ('-created',)},
        ),
    ]
